name: Bug Report
description: Report a reproducible bug in gameplay, protocol, server, or client.
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report. Please include concrete reproduction details so maintainers can verify quickly.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Gameplay rules / engine
        - Server API / WebSocket
        - Shared schema / protocol
        - Client UI
        - Deployment / infrastructure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Commit / Version
      description: Commit SHA, release tag, or branch used.
      placeholder: "e.g. 0f68d23 (main)"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Node version, and whether this is local/dev/prod.
      placeholder: |
        macOS 14, Chrome 122, Node 20.x
        Local dev via pnpm dev:server + pnpm dev:client
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Include exact steps, match setup, and actions in order.
      placeholder: |
        1. Create match with damageMode=per-turn
        2. Join second player
        3. Deploy cards ...
        4. Attack ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: input
    id: rule_id
    attributes:
      label: Related Rule ID (if known)
      description: Use IDs from docs/RULES.md (e.g. PHX-DAMAGE-001).
      placeholder: "PHX-..."

  - type: textarea
    id: evidence
    attributes:
      label: Logs / Screenshots / Payloads
      description: Paste relevant logs, API payloads, console output, screenshots.
      render: text

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-Submission Checks
      options:
        - label: I searched existing issues for duplicates.
          required: true
        - label: I can reproduce this on the latest main branch.
          required: true
